### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by Lautarotetamusa** [Lautarotetamusa/Agribussiness#1]
- [ ] Agregar parametro a GET /productos para obtener solo los productos que tienen fichas tecnicas.
- [x] Ruta descargar lista de precios, se debe generar un archivo .pdf con todos los productos en el sistema.
- [x] GET /personas no deberia listar a la persona loggeada ni al invitado.
- [x] Agregar un limite al /messages (50)
